---
title: "Code for Rebuttal Figures"
format: 
    html:
      toc: true
      self-contained: true
      highlight-style: github
      code-line-numbers: true
      code-fold: true
editor: source
editor_options: 
  chunk_output_type: console
#params:
#  datadir: 'test'
#  nmethod_range:
#  ground_truth:
#  nns: 6
#  name: "noname"
#  nclust_range:
#  nsmoothest: 30
#  obs_filter: NULL
---

## Retrieve parameters

```{r display-params}
datadir <- "data/other-datasets"
stub <- "xenium_mouse_brain_SergioSalas"
# name <- "fig3"
# nclust_range <- c(5,7,9)
# nmethod_range <- 5:12


# gt <- c("parcellation_structure","parcellation_substructure")
# k <- 6
# nclust_range <- c(16,20,24)
# nmethod_range <- c(3,4,5,6,7,8,9)
# nsmoothest <- c(30)
# obs_filter <- 'parcellation_division=="TH" | parcellation_structure=="ZI"'

# if datadir ends in `/`, it screws up the parsing of method names,
# so add a check for it
stopifnot(tail(strsplit(datadir,"")[[1]],1)!="/")

```

## Packages / functions

```{r load-packages}
suppressPackageStartupMessages({
  library(SpatialExperiment)
  library(dplyr)
  library(ggplot2)
  library(cowplot)
  library(clue)
  library(khroma)
  library(scran)
  library(limma)
  library(tibble)
  library(readr)
  library(ggrepel)
  library(mclust)
  library(pheatmap)
  library(fastDummies)
  library(randomcoloR)
  library(STexampleData)
  library(reshape2)
  library(poem)
  library(gridExtra)
})
source("utils.R")
```


## Load data 

```{r load-data}


base_clusterings <- read_tsv(file.path(datadir, 
                                       paste0("combined_domains_", stub, ".tsv")),
                             show_col_types = FALSE)
# base_clusterings <- read_tsv(file.path(datadir, 
#                                        "combined_methods.tsv"),
#                              show_col_types = FALSE)
colnames(base_clusterings)[1] <- "barcode_id"
# coords <- base_clusterings[,c("x","y")]
# base_clusterings[,c("label","label_confidence","x","y","z")] <- NULL


# "-" this causes problems later (with LCA)
colnames(base_clusterings) <- gsub("SCAN-IT", "SCANIT", 
                                   colnames(base_clusterings))

# coords <- read_tsv(file.path(datadir,
#                              "coordinates_visium_hd.tsv"),
#                              show_col_types = FALSE)
# colnames(coords)[1] <- "barcode_id"
# 
# head(coords)
# head(base_clusterings[,1:5])
# 
# m <- match(base_clusterings$barcode_id, coords$barcode_id)
# sum(is.na(m))
# 
# coords <- coords[m,]



rownames(base_clusterings) <- NULL
base_clusterings <- base_clusterings %>%
  as.data.frame %>%
  column_to_rownames("barcode_id")



# all(rownames(base_clusterings)==coords$barcode_id)


```


## Smoothness-entropy of base clusterings (not used)

```{r smoothness-entropy, fig.width=8, fig.height=6, eval=TRUE}


# # find number of actual clusters per column
real_n <- apply(base_clusterings, 2,
                function(u) length(unique(u)))
table(real_n)

base_clusterings <- base_clusterings[,real_n>1]


real_n <- apply(base_clusterings, 2,
                function(u) length(unique(u)))
table(real_n)


# > library(parallel)
# > detectCores()
# [1] 8


# # large compute time.
# mse <- apply(base_clusterings, 2,
#              function(u) spot_entropy(coords[,c("x","y")],u, k=10))
# se <- colMeans(mse)


# library(parallel)
# library(doParallel)
# cl <- makeCluster(detectCores()-2)
# registerDoParallel(cl)
# mse <- foreach(i =  1:NCOL(base_clusterings)) %dopar% {
#   spot_entropy(coords[,c("x","y")],base_clusterings[,i], k=10)
# }
# stopCluster(cl)
# 
# 
# se <- sapply(mse, mean)
# names(se) <- colnames(base_clusterings)

```


## Similarity of all clusterings: 

```{r clustering-similarities, fig.height=9, fig.width=10}
# keepers <- names(bases)
# aris_all <- calc_aris(cbind(base_clusterings,
#                             annotation=cd[,"ground_truth"]))
# all(colnames(aris_all) %in% names(all_mses))

# aris_all <- calc_aris(base_clusterings)

# subsample to make faster
set.seed(14102025)
if(ncol(base_clusterings) < 20) {
  s <- seq_len(ncol(base_clusterings))
} else {
  s <- sample(ncol(base_clusterings),50,replace = FALSE)
}
system.time( aris_all <- calc_aris(base_clusterings[,s]) )


# anno_row <- data.frame(entropy = all_mses)
# rownames(anno_row) <- names(all_mses)

# anno_row <- data.frame(n_clust = real_n)
# rownames(anno_row) <- names(real_n)

anno_row <- data.frame(n_clust = real_n[s])
rownames(anno_row) <- names(real_n[s])

# spot check
all(names(real_n[s])==rownames(aris_all))

#anno_row$se <- se[names(real_n[s])]

# anno_row$panelA <- "not-shown"
# anno_row$panelA[rownames(anno_row)=="annotation"] <- "annotation"

ann_colors = list(
    n_clust = c("5" = "#1B9E77", "7" = "orange", "9" = "firebrick")
)


# ph_all <- pheatmap(aris_all, fontsize = 5, 
#                    annotation_row = anno_row,
#                    annotation_colors = ann_colors)

anno_row1 <- anno_row
ss <- strsplit(rownames(anno_row1), "_")
method <- sapply(ss, .subset, 1)
methods <- method  %>% unique #%>% setdiff("annotation")

mat <- matrix(0, nrow = nrow(anno_row1), 
       ncol = length(methods), 
       dimnames = list(rownames(anno_row1), methods))

anno_row1 <- cbind(anno_row1, mat)

for(meth in methods) {
  ann_colors[[meth]] <- c("0" = "grey95", "1" = "black")
  anno_row1[method==meth,meth] <- 1
}

cats_list <- list()
cats_list$`Embedding-Clustering` <- c("BANKSY","stardust","spatialGE",
                                      "CellCharter",
                                      "meringue","SCANIT")
cats_list$DL <- c("spaGCN","SEDR","SpaceFlow","SOTIP",
                  "GraphST","STAGATE")
cats_list$`Bayesian-HMRF` <- c("BayesSpace","precast","scMEB",
                               "DRSC","SpiceMix",
                               "maple","bass","Giotto")
cats_list$`non-spatial` <- c("scanpy", "seurat")

# scMEB
# Giotto

# > setdiff(unname(unlist(cats_list)), colnames(anno_row1))
# [1] "scMEB"  "Giotto"
# 
# > colnames(anno_row1)
#  [1] "entropy"     "n_clust"     "scanpy"      "SOTIP"       "DRSC"       
#  [6] "seurat"      "CellCharter" "BayesSpace"  "STAGATE"     "stardust"   
# [11] "SpiceMix"    "BANKSY"      "spatialGE"   "maple"       "spaGCN"     
# [16] "SEDR"        "meringue"    "precast"     "SC"          "bass"       
# [21] "SpaceFlow"   "SCANIT"      "GraphST"   

cats <- matrix(0, nrow = nrow(anno_row1),
               ncol = length(cats_list),
               dimnames = list(rownames(anno_row1), names(cats_list)))
anno_row1 <- cbind(anno_row1, cats)

for(cat in 1:length(cats_list)) {
  ann_colors[[names(cats_list)[cat]]] <- c("0" = "grey85", "1" = "darkorange")
  anno_row1[method %in% cats_list[[cat]],names(cats_list)[cat]] <- 1
}

anno_row1$n_clust <- NULL

greens <- colorRampPalette(RColorBrewer::brewer.pal(n = 7,
                                name = "Greens"))(100)


ph_all <- pheatmap(aris_all, fontsize = 5, 
                   annotation_row = anno_row1,
                   annotation_colors = ann_colors,
                   color = greens,
                   annotation_legend = FALSE)

save_pheatmap_pdf(ph_all, paste0("rebuttal-", stub, ".pdf"), width=13, height=9)


```


## sessionInfo()

```{r sessioninfo}
sessionInfo()
```

